spring.application.name=userService

spring.kafka.producer.bootstrap-servers=172.17.255.255:9092
spring.kafka.consumer.group-id=userinfo-consumer-group
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer= com.project.userService.deserializer.UserInfoDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.topic.name=testingself
spring.kafka.consumer.properties.spring.json.type.mapping=auth:com.project.userService.entities.UserInfoDto

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:172.17.255.255}:${MYSQL_PORT:3306}/${MYSQL_DB:userservice}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
server.port=3306

logging.level.org.springframework.security=DEBUG
